# Generated by Django 3.2.8 on 2021-12-03 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0002_completeuserdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuserdetails',
            name='Aadhaar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CUD_set', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('Pan_no', models.CharField(max_length=15, null=True)),
                ('BPL_no', models.CharField(max_length=15, null=True)),
                ('Ration_no', models.CharField(max_length=15, null=True)),
                ('Mobile_no', models.CharField(max_length=10, null=True)),
                ('Voter_id', models.CharField(max_length=15, null=True)),
                ('Electricity_bill', models.CharField(max_length=20, null=True)),
                ('Bank_Acc_no', models.IntegerField(null=True)),
                ('IFSC_Code', models.CharField(max_length=12, null=True)),
                ('MICR_Code', models.CharField(max_length=15, null=True)),
                ('Bank', models.CharField(max_length=30, null=True)),
                ('Branch', models.CharField(max_length=30, null=True)),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SwayamSeva.completeuserdetails')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
    ]
