# Generated by Django 3.2.8 on 2021-12-03 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0003_auto_20211204_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SwayamSeva.completeuserdetails'),
        ),
        migrations.CreateModel(
            name='Schemes',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Scheme_Name', models.CharField(max_length=15)),
                ('Aadhaar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Schemes',
            },
        ),
    ]
