# Generated by Django 3.2.8 on 2021-12-03 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0004_auto_20211204_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeuserdetails',
            name='Aadhaar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CUD_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
