# Generated by Django 3.2.8 on 2021-12-04 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0005_alter_completeuserdetails_aadhaar'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchemes',
            fields=[
                ('schemes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SwayamSeva.schemes')),
            ],
            bases=('SwayamSeva.schemes',),
        ),
        migrations.AddField(
            model_name='schemes',
            name='Date_Applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Applied'),
            preserve_default=False,
        ),
    ]
