# Generated by Django 3.2.8 on 2021-12-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0006_auto_20211204_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySchemes',
        ),
    ]
