# Generated by Django 3.2.8 on 2021-12-04 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0007_delete_myschemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeuserdetails',
            name='Date_Submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submitted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='Date_Submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Submitted'),
            preserve_default=False,
        ),
    ]
