# Generated by Django 3.2.8 on 2021-12-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0009_alter_schemes_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doc_set', to='SwayamSeva.completeuserdetails'),
        ),
    ]
