# Generated by Django 3.2.8 on 2021-12-19 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0014_alter_documents_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doc_set', to='SwayamSeva.completeuserdetails'),
        ),
    ]
