# Generated by Django 3.2.8 on 2021-12-19 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0016_auto_20211219_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Mobile_no',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Please Enter a 10 digit Mobile No.', regex='^.{10}$')]),
        ),
    ]
