# Generated by Django 3.2.8 on 2022-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0019_rename_email_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Approved', 'Approved')], default='Pending', max_length=15, verbose_name='Status'),
        ),
    ]
