# Generated by Django 3.2.6 on 2022-06-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0022_alter_userdetails_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='avatar',
        ),
    ]
