# Generated by Django 3.2.6 on 2022-06-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SwayamSeva', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='Uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doc_set', to='SwayamSeva.completeuserdetails'),
        ),
    ]
